### PR TITLE
support `type_one_side` along with `exclude_types`

### PR DESCRIPTION
**Pull request by njzjz**
This PR supports `type_one_side` along with `exclude_types`, by reusing the same NN parameters.

### CODE REVIEW

**Review by wanghan-iapcm — CHANGES_REQUESTED** [review]
This PR is not covered by UT. 

Please make sure 
1. the model works as expected when `exclude_types` is set with `type_one_side`
2. the compressed models (se_a and se_r) gives identical prediction as the original model.

**Comment by njzjz** [comment]
The model should work as expected as shown below.
image

**Comment by njzjz** [comment]
For compression, I still got the same error message as I mentioned in #1388, which may need help from @denghuilu.

**Comment by wanghan-iapcm** [comment]
> The model should work as expected as shown below. image

This is **not** a unittest.

**Comment by denghuilu** [comment]
> For compression, I still got the same error message as I mentioned in #1388, which may need help from @denghuilu.

I'll fix it this week.

**Comment by njzjz** [comment]
@wanghan-iapcm @denghuilu Unittests were added. Please review.

**Review by wanghan-iapcm — APPROVED** [review]

**Comment by wanghan-iapcm** [comment]
LGTM

**Review by denghuilu — APPROVED** [review]

**Pull request merged**
