### PR TITLE
remove the dependency on `inputs` from `inputs_zero`

### PR DESCRIPTION
**Pull request by njzjz**
When profiling on multiple CPU threads, I notice that `inputs_zero` always runs after descriptor is computed. However, Some threads have nothing to do during `ProdEnvMatA`.

image

`inputs_zero` can be used to fill waiting time and runs with `ProdEnvMatA` at the same time...

image

(cherry picked from commit e704b4af1df7c23465615454bf7dfc0fc2f8d18f)

### CODE REVIEW

**Review by wanghan-iapcm — COMMENTED** [review]
It is not a good idea to change the **interface** of the `EnerFitting`  for the sake of little performance improvement.

**Comment by njzjz** [comment]
> It is not a good idea to change the **interface** of the `EnerFitting` for the sake of little performance improvement.

I can add it to `input_dict` instead.

**Comment by njzjz** [comment]
Done. It will also work when there's nothing in the `input_dict`.

**Review by wanghan-iapcm — APPROVED** [review]
I approve this PR, but I really do not like the `input_dict`, which makes the interfaces unclear...

**Pull request merged**
