### PR TITLE
Generate CUDA stubs dynamically

### PR DESCRIPTION
**Pull request by njzjz**
This PR follows https://github.com/google/tsl/commit/726288eb9a20b77600c592a3875c8887a376e1b5 and has the same motivation as that commit. `libcudart.so` stubs using assembly language are generated dynamically by [implib.so](https://github.com/yugr/Implib.so) during CMake execution, instead of storing many versions of stub files in the repository.

Implib.so is vendored in `source/3rdparty` directory in the size of 156KB and slightly modified (to allow no CUDA library found).

### CODE REVIEW

**Comment by njzjz** [comment]
@caic99 Could you take a look at the NVIDIA machine... It worked fine in #2841 but appears to have `apt` errors in this PR.

```
You might want to run 'apt --fix-broken install' to correct these.
  The following packages have unmet dependencies:
   nvidia-dkms-535 : Depends: nvidia-kernel-common-535 (>= 535.104.05) but 535.[86](https://github.com/deepmodeling/deepmd-kit/actions/runs/6361031399/job/17275175999?pr=2884#step:4:88).10-0ubuntu1 is to be installed
   nvidia-driver-535 : Depends: nvidia-kernel-common-535 (>= 535.104.05) but 535.86.10-0ubuntu1 is to be installed
                       Recommends: libnvidia-compute-535:i386 (= 535.104.05-0ubuntu0.22.04.4)
                       Recommends: libnvidia-decode-535:i386 (= 535.104.05-0ubuntu0.22.04.4)
                       Recommends: libnvidia-encode-535:i386 (= 535.104.05-0ubuntu0.22.04.4)
                       Recommends: libnvidia-fbc1-535:i386 (= 535.104.05-0ubuntu0.22.04.4)
                       Recommends: libnvidia-gl-535:i386 (= 535.104.05-0ubuntu0.22.04.4)
  E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

**Comment by njzjz** [comment]
Since the machine to test CUDA is broken, I've tested it on the local machine.

**Review by wanghan-iapcm — APPROVED** [review]

**Comment by caic99** [comment]
> @caic99 Could you take a look at the NVIDIA machine... It worked fine in #2841 but appears to have `apt` errors in this PR.
> 
> ```
> You might want to run 'apt --fix-broken install' to correct these.
>   The following packages have unmet dependencies:
>    nvidia-dkms-535 : Depends: nvidia-kernel-common-535 (>= 535.104.05) but 535.[86](https://github.com/deepmodeling/deepmd-kit/actions/runs/6361031399/job/17275175999?pr=2884#step:4:88).10-0ubuntu1 is to be installed
>    nvidia-driver-535 : Depends: nvidia-kernel-common-535 (>= 535.104.05) but 535.86.10-0ubuntu1 is to be installed
>                        Recommends: libnvidia-compute-535:i386 (= 535.104.05-0ubuntu0.22.04.4)
>                        Recommends: libnvidia-decode-535:i386 (= 535.104.05-0ubuntu0.22.04.4)
>                        Recommends: libnvidia-encode-535:i386 (= 535.104.05-0ubuntu0.22.04.4)
>                        Recommends: libnvidia-fbc1-535:i386 (= 535.104.05-0ubuntu0.22.04.4)
>                        Recommends: libnvidia-gl-535:i386 (= 535.104.05-0ubuntu0.22.04.4)
>   E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
> ```

Hi @njzjz ,
Sorry for the late reply since I just came back from my vacation. 
Please note that the environment for a self-hosted runner is [persistent](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#hardening-for-self-hosted-runners), and the `apt-get` commands might have conflict with other workflows executed on this runner.
I've manually fixed the broken packages. I would strongly suggest running this workflow in a docker container.

**Comment by njzjz** [comment]
> I would strongly suggest running this workflow in a docker container.

I'll have a try.

**Pull request merged**
