### PR TITLE
[Paddle Backend] Support GPU train/test/inference/LAMMPS with PaddlePaddle backend for water se_e2_a

### PR DESCRIPTION
**Pull request by HydrogenSulfate**
- Support GPU train/test/inference/LAMMPS with PaddlePaddle Backend for water se_e2_a

- Summary can be previewed in [README.md](https://github.com/HydrogenSulfate/deepmd-kit/tree/add_ddle_backend_polish_ver#deepmd-kitpaddlepaddle-backend)

- (GPU)Test alignment(almost same):
    
    image

- (GPU)Trainig alignment(slighly better than TF for all metrics):
    
    image

- (GPU)Inference with LAMMPS:
    
    image

### CODE REVIEW

**Comment by njzjz** [comment]
I feel that firstly there should be a branch to be based on; otherwise, it is hard to see what this PR does.

**Comment by HydrogenSulfate** [comment]
> I feel that firstly there should be a branch to be based on; otherwise, it is hard to see what this PR does.

I guess I could open a temporary PR to `devel` branch? As the code difference can be distinguished.

**Comment by njzjz** [comment]
Perhaps backup the current `paddle` to another branch `paddle_bak` and make `paddle` to be 617035662b1cb72e72a4cbc7c0fd3ad8a846657e, which this PR is based on. cc @wanghan-iapcm

**Comment by njzjz** [comment]
Or, should we wait for v3 for the multiple backend refactor?

**Comment by HydrogenSulfate** [comment]
> Perhaps backup the current `paddle` to another branch `paddle_bak` and make `paddle` to be [6170356](https://github.com/deepmodeling/deepmd-kit/commit/617035662b1cb72e72a4cbc7c0fd3ad8a846657e), which this PR is based on. cc @wanghan-iapcm

This might be fine, because the current `paddle` branch can not be executed any more, several errors raised for the update of incompatible code of paddle framework during 2021 ~ 2023.

**Comment by HydrogenSulfate** [comment]
> Or, should we wait for v3 for the multiple backend refactor?

I guess this is better than make paddle(or other framework) as an independent branch for inevitable backward between master branch and paddle branch, but I understand multiple-backend is relatively large refactoring and need much time to verify correctness between tf ver and multiple-backend ver. So if there is any timeline for multiple-backend project can be revealed? Thanks for replying anyway.

**Comment by wanghan-iapcm** [comment]
> Perhaps backup the current `paddle` to another branch `paddle_bak` and make `paddle` to be [6170356](https://github.com/deepmodeling/deepmd-kit/commit/617035662b1cb72e72a4cbc7c0fd3ad8a846657e), which this PR is based on. cc @wanghan-iapcm

I would suggest creating the new paddle branch.

**Comment by njzjz** [comment]
> So if there is any timeline for multiple-backend project can be revealed?

There's no timeline. So, I created a new branch.

@HydrogenSulfate could you revert the code formatting rules? There are too many formatting changes in this PR.

**Comment by HydrogenSulfate** [comment]
> > So if there is any timeline for multiple-backend project can be revealed?
> 
> There's no timeline. So, I created a new branch.
> 
> @HydrogenSulfate could you revert the code formatting configurations? There are too many formatting changes in this PR.

I create another PR for revert code formatting #3078 , but I remove `mirrors-csslint` plugin for this is not compatible with `GLIBC!=0.28`.

**Comment by njzjz** [comment]
I've merged #3078.

**Pull request closed without merging**
