### PR TITLE
use setuptools_scm instead of setuptools-git-version

### PR DESCRIPTION
**Pull request by njzjz**
Then, we can use `python setup.py sdist` to package the source, and use `twine upload dist/*` to upload it to [pypi.org](https://pypi.org/simple). Users can use `pip install deepmd-kit` to install the python interface directly.

### CODE REVIEW

**Comment by njzjz** [comment]
why test fail...

**Comment by njzjz** [comment]
为啥分了一台gcc=5.4的机器……

**Comment by amcadmus** [comment]
Why does the test fail on a machine with gcc==5.4? Could you paste the error log?

**Comment by amcadmus** [comment]
2019-07-30-205606_1854x590_scrot
I see it....

**Comment by amcadmus** [comment]
The official tensorflow distribution was built with gcc==4.8 and the deepmd-kit should be built with the same gcc...

**Comment by njzjz** [comment]
see tensorflow/tensorflow#27067

**Pull request merged**
