### PR TITLE
user specified precision for embedding and fitting nets

### PR DESCRIPTION
**Pull request by GeiduanLiu**
support only tf.float16, tf.float32 and tf.float64. 
tf.float16 may cause nan problem

### CODE REVIEW

**Comment by njzjz** [comment]
It’s not necessary to specify precision for custom op?

**Comment by GeiduanLiu** [comment]
> It’s not necessary to specify precision for custom op?

We can specify precision for custom op while compiling.

**Comment by amcadmus** [comment]
> It’s not necessary to specify precision for custom op?

The precision of the custom op was determined at compile time. What Geiduan implemented is to change the floating point precision only in the NNs.

**Comment by njzjz** [comment]
> > It’s not necessary to specify precision for custom op?
> 
> The precision of the custom op was determined at compile time. What Geiduan implemented is to change the floating point precision only in the NNs.

I see. Is it possible to compile both precision? I think tensorflow must have done it, so we do not need to recompile tensorflow for different precision.

**Pull request merged**
