### PR TITLE
CI: set up CUDA environment

### PR DESCRIPTION
**Pull request by njzjz**
## Summary by CodeRabbit

- **New Features**
  - Introduced a new Conda environment configuration for CUDA development, supporting TensorFlow and PyTorch with CUDA.

- **Chores**
  - Updated workflow to use `mamba-org/setup-micromamba` for setting up the Python environment.
  - Enhanced environment setup with specific configurations for TensorFlow and PyTorch.
  - Improved and streamlined CUDA and PyTorch test commands.

### CODE REVIEW

**Comment by njzjz** [comment]
```
  Transaction starting
  critical libmamba Download error (28) Timeout was reached [https://conda.anaconda.org/conda-forge/linux-64/unzip-6.0-h7f98852_3.tar.bz2]
      Operation too slow. Less than 30 bytes/sec transferred the last 60 seconds
  Error: The process '/github/home/micromamba-bin/micromamba' failed with exit code 1
```

@caic99 any idea?

**Comment by caic99** [comment]
> ```
>   Transaction starting
>   critical libmamba Download error (28) Timeout was reached [https://conda.anaconda.org/conda-forge/linux-64/unzip-6.0-h7f98852_3.tar.bz2]
>       Operation too slow. Less than 30 bytes/sec transferred the last 60 seconds
>   Error: The process '/github/home/micromamba-bin/micromamba' failed with exit code 1
> ```
> 
> @caic99 any idea?

Nothing but poor internet connection. 
@njzjz Maybe you could use `t4` runner for debugging purpose first.
@iProzd Where is this instance located?

**Comment by njzjz** [comment]
> > ```
> 
> >   Transaction starting
> 
> >   critical libmamba Download error (28) Timeout was reached [https://conda.anaconda.org/conda-forge/linux-64/unzip-6.0-h7f98852_3.tar.bz2]
> 
> >       Operation too slow. Less than 30 bytes/sec transferred the last 60 seconds
> 
> >   Error: The process '/github/home/micromamba-bin/micromamba' failed with exit code 1
> 
> > ```
> 
> > 
> 
> > @caic99 any idea?
> 
> 
> 
> Nothing but poor internet connection. 
> 
> @njzjz Maybe you could use `t4` runner for debugging purpose first.
> 
> @iProzd Where is this instance located? 

I see the same error with t4.

**Comment by caic99** [comment]
> I see the same error with t4.

No ideas 😿

**Comment by njzjz** [comment]
I decided to give up this PR and try another way.

**Pull request closed without merging**
