### PR TITLE
Collect

### PR DESCRIPTION
**Pull request by Qubit-Fernand**
# DPA collect
This python  script will automatically convert the given path into standard data tree of DPA
## Parameters
-i: input path -o: ouput path -t: sparse system threshold (default: 10)

### CODE REVIEW

**Comment by Qubit-Fernand** [comment]
Retry

**Comment by Qubit-Fernand** [comment]
Retry

**Comment by Qubit-Fernand** [comment]
# DPA collect
This python script will automatically convert the given path into standard data tree of DPA
## Parameters
-i: input path -o: ouput path -t: sparse system threshold (default: 10)

**Comment by njzjz** [comment]
pre-commit.ci run

**Review by wanghan-iapcm — CHANGES_REQUESTED** [review]
Please describe what does this PR implement. 
Please provide CLI for your new function.

**Comment by wanghan-iapcm** [comment]
> # DPA collect
> 
> This python script will automatically convert the given path into standard data tree of DPA
> ## Parameters
> 
> -i: input path -o: ouput path -t: sparse system threshold (default: 10)

What is supposed to be in the "given path"? I also do not understand what is the "standard data tree of DPA"

**Comment by Qubit-Fernand** [comment]
> > # DPA collect
> > This python script will automatically convert the given path into standard data tree of DPA
> > ## Parameters
> > -i: input path -o: ouput path -t: sparse system threshold (default: 10)
> 
> What is supposed to be in the "given path"? I also do not understand what is the "standard data tree of DPA"

Given path means the abs-path of input dataset. For example: /root/dataset/Si, so as the output path.
Standard data tree is the discussion result of DPA project, which is convenient for MLOps workflow, this python script has already been adopted in [https://launching.mlops.dp.tech] dpa-upload module:

[https://dptechnology.feishu.cn/wiki/wikcnTaIzNOl3eC5FKYGWiBgi1d]

**Pull request closed without merging**
