### PR TITLE
Sync gitee

### PR DESCRIPTION
**Pull request by tuoping**
I'm not sure if this works. How do I test this?

### CODE REVIEW

**Review by njzjz — CHANGES_REQUESTED** [review]
Seems that you didn't add a private key? Do you know how to create the pair of keys?

**Comment by tuoping** [comment]
If you mean create a public key of my address to gitee or github, I know this. But this means the sync has to be performed via me or someone else. Or do you mean there is a way to add a key of github to gitee? Sorry, I tried to find this and failed.

**Comment by njzjz** [comment]
A pair of SSH key is divided into a public key and a private key. You need to add the private key here (into GitHub Action secrets) and add the public key into Gitee settings.
https://www.ssh.com/academy/ssh/public-key-authentication

**Comment by tuoping** [comment]
That is brilliant. I was stupid, @rz.

**Comment by tuoping** [comment]
It's working now. High five, dude!!!

**Review by njzjz — APPROVED** [review]

**Pull request merged**
