### PR TITLE
support fitting net

### PR DESCRIPTION
**Pull request by wanghan-iapcm**
- also add doc string for the embedding net

### CODE REVIEW

**Comment by wanghan-iapcm** [comment]
I find we could have written a uniform implementation of embedding and fitting networks across platforms. We only have to make the interface of MLPLayer uniform across platforms. @njzjz what do you think?

**Comment by njzjz** [comment]
> I find we could have written a uniform implementation of embedding and fitting networks across platforms. We only have to make the interface of MLPLayer uniform across platforms. @njzjz what do you think?

Agree

**Comment by wanghan-iapcm** [comment]
> > I find we could have written a uniform implementation of embedding and fitting networks across platforms. We only have to make the interface of MLPLayer uniform across platforms. @njzjz what do you think?
> 
> Agree

I will contribute in a future PR.

**Comment by wanghan-iapcm** [comment]
> > I find we could have written a uniform implementation of embedding and fitting networks across platforms. We only have to make the interface of MLPLayer uniform across platforms. @njzjz what do you think?
> 
> Agree

The first step: #3138

**Pull request merged**
