### PR TITLE
Add a script to detect model version

### PR DESCRIPTION
**Pull request by Yi-FanLi**
This PR adds a script in deepmd/utils to detect the version of a Deep Potential model.

### CODE REVIEW

**Review by njzjz — CHANGES_REQUESTED** [review]
A test can be added here

https://github.com/deepmodeling/deepmd-kit/blob/94c24c18e5afb5d48473db8da54dab745eff9aea/source/tests/test_deeppot_a.py#L726-L727

**Review by njzjz — APPROVED** [review]
LGTM

**Comment by njzjz** [comment]
please fix the pre-commit error

**Comment by Yi-FanLi** [comment]
> please fix the pre-commit error

Yes. Now I have fixed it.

**Review by njzjz — APPROVED** [review]

**Pull request merged**
