### PR TITLE
LAMMPS: Use of “override” instead of “virtual”

### LINKED ISSUE #1855: LAMMPS: Use of “override” instead of “virtual”
### Summary

See LAMMPS documentation https://docs.lammps.org/Developer_updating.html#use-of-override-instead-of-virtual for details.

### Detailed Description

> Changed in version 17Feb2022.
>
> Since LAMMPS requires C++11 we switched to use the “override” keyword instead of “virtual” to indicate polymorphism in derived classes.

### Further Information, Files, and Links

_No response_

### PR DESCRIPTION
**Pull request by njzjz**
fix #1855.

### CODE REVIEW

**Comment by njzjz** [comment]
Looks good.

**Review by wanghan-iapcm — APPROVED** [review]

**Comment by ZhengdQin** [comment]
Hi jinzhe,

I want commit based on your commit, could you please tell me how to pass this checks. I got the same problems. You can find my code at https://github.com/ZhengdQin/deepmd-kit/tree/ascend . Thanks. 
image

**Comment by njzjz** [comment]
The old checks might be out-of-date. @wanghan-iapcm Is there any reason not to merge with the latest commit?

**Comment by njzjz** [comment]
By the way, @ZhengdQin could you send me your email address?

**Comment by ZhengdQin** [comment]
> By the way, @ZhengdQin could you send me your email address?

zhengdqin@gmail.com is my email. I tred to merge to the latest commit but it leads to some new problems, and my colleagues want to use it as soon as possible, so I decided to merge to ascend branch first and try to merge to the latest commit later.

**Pull request merged**
