### PR TITLE
add code comment for InputNlist struct

### PR DESCRIPTION
**Pull request by denghuilu**

### CODE REVIEW

**Comment by njzjz** [comment]
I forgot to mention.. Use the doxygen style introduced here https://wiki.rdkcentral.com/plugins/servlet/mobile?contentId=20807878#content/view/20807878

**Comment by denghuilu** [comment]
@njzjz Any suggestion to solve this problem?
image

**Comment by denghuilu** [comment]
> I forgot to mention.. Use the doxygen style introduced here https://wiki.rdkcentral.com/plugins/servlet/mobile?contentId=20807878#content/view/20807878

OK

**Comment by njzjz** [comment]
https://github.com/deepmodeling/deepmd-kit/blob/ee0f6e6aa789e06a297d5e6f76000356b808474e/.github/workflows/test_python.yml#L57-L64

There should be a wrong cache of pypi index. However, GitHub provides no way to clean the cache.

**Comment by njzjz** [comment]
See also https://pip.pypa.io/en/stable/topics/caching/#http-responses

**Review by njzjz — APPROVED** [review]

**Comment by njzjz** [comment]
Finally, someone has the same cache issue: matplotlib/matplotlib#20834

**Pull request merged**
