### PR TITLE
fix device UT error

### PR DESCRIPTION
**Pull request by denghuilu**

### CODE REVIEW

**Review by njzjz — APPROVED** [review]

**Review by pkulzy — COMMENTED** [review]
I tested it on ROCm platform. . The results showed that there are 23 skipped.
'''
Ran 265 tests in 974.050s
OK (skipped=23) 
'''
is that normal?

**Comment by denghuilu** [comment]
> I tested it on ROCm platform. . The results showed that there are 23 skipped.
> 
> '''
> 
> Ran 265 tests in 974.050s
> 
> OK (skipped=23) 
> 
> '''
> 
> is that normal?

The same as cpu and gpu.

**Review by pkulzy — APPROVED** [review]

**Comment by pkulzy** [comment]
> > I tested it on ROCm platform. . The results showed that there are 23 skipped.
> > '''
> > Ran 265 tests in 974.050s
> > OK (skipped=23)
> > '''
> > is that normal?
> 
> The same as cpu and gpu.

But why did the test skip

**Comment by amcadmus** [comment]
> > > I tested it on ROCm platform. . The results showed that there are 23 skipped.
> > > '''
> > > Ran 265 tests in 974.050s
> > > OK (skipped=23)
> > > '''
> > > is that normal?
> > 
> > 
> > The same as cpu and gpu.
> 
> But why did the test skip

Skipped when the tf version is not satisfied with the UT.  see
https://github.com/deepmodeling/deepmd-kit/blob/1a25414dcd18b12316250baa330b690f3f5510fe/source/tests/test_deepdipole.py#L105

**Pull request merged**
