### PR TITLE
Doc api cc

### PR DESCRIPTION
**Pull request by tuoping**
Made api_cc.rst in doc/development/

### CODE REVIEW

**Review by amcadmus — CHANGES_REQUESTED** [review]
We haven't provided any documentation string in `deepmd.DeepPot` nor `deepmd.DeepPotModelDevi`, so I do not understand how this commit works.

**Comment by tuoping** [comment]
I found only doxygen to generate C++ api. But it cannot be installed with pip. So I had to add a precompiled directory xml/. Is there a way to include an external package by setup.py? @njzjz

**Comment by njzjz** [comment]
The following question said doxygen had been installed in the readthedocs.
https://stackoverflow.com/questions/36064976/using-doxygen-in-read-the-docs

**Comment by njzjz** [comment]
See also https://breathe.readthedocs.io/en/latest/readthedocs.html.

**Comment by tuoping** [comment]
It's working now.
Preview here:
https://deepmd-kit-testdoc.readthedocs.io/en/doc-api_cc/development/api_cc.html
Thank you all.

**Comment by tuoping** [comment]
I included an extra package "exhale". C++ API display is looking a lot better now.
Preview here:
https://deepmd-kit-testdoc.readthedocs.io/en/doc-api_cc/API_CC/api_cc.html

**Comment by njzjz** [comment]
https://deepmd-kit-testdoc.readthedocs.io/en/doc-api_cc/API_CC/namespace_tensorflow.html

We have tensorflow namespace in the code?

**Comment by njzjz** [comment]
https://github.com/deepmodeling/deepmd-kit/blob/5a8bc2c97f6c16cf783a2802ffa8da4ddd49c105/source/api_cc/include/custom_op.h#L14

@denghuilu Is it possible to remove this line?

**Comment by tuoping** [comment]
I excluded namespace in api_cc.rst. 
Preview here:
https://deepmd-kit-testdoc.readthedocs.io/en/doc-api_cc/API_CC/api_cc.html

**Comment by njzjz** [comment]
@tuoping Could you give an example of how to write documents for APIs? Then I can fill it.

**Comment by tuoping** [comment]
Use exhale to invoke doxygen and then generate a structured api_cc
https://exhale.readthedocs.io/en/latest/usage.html#setup-the-extensions-in-conf-py
Also
https://stackoverflow.com/questions/59990484/doxygensphinxbreatheexhale

**Comment by njzjz** [comment]
@tuoping do you know what's wrong with my commit? It doesn't work.

**Comment by tuoping** [comment]
I recompiled it on readthedocs, and it worked.
Preview here:
https://deepmd-kit-testdoc.readthedocs.io/en/doc-api_cc/API_CC/classdeepmd_1_1DeepPot.html#exhale-class-classdeepmd-1-1deeppot

**Review by amcadmus — APPROVED** [review]

**Review by amcadmus — APPROVED** [review]

**Pull request merged**
